version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    restart: unless-stopped

  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - app-network
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:v1.10.0
    container_name: qdrant
    ports:
      - "6333:6333"
    environment:
      QDRANT__SERVICE__HTTP_PORT: 6333
    volumes:
      - qdrant_storage:/qdrant/storage
    networks:
      - app-network
    restart: unless-stopped

volumes:
  mongodb_data:
  qdrant_storage:

networks:
  app-network:

    driver: bridge


