[project]
name = "embedder"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.13",
    "numpy>=2.3.1",
    "pydantic>=2.11.7",
    "sentence-transformers>=4.1.0",
    "uvicorn>=0.34.3",
]
